#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d       ﭮ 
#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor -d 一 二 三 四 五 六 七 八 九
#bspc monitor -d         

bspc config border_width         2
bspc config window_gap           5
bspc config focused_border_color "#81a1c1"
bspc config normal_border_color  "#4c566a"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
${HOME}/.local/scripts/./bg-change.sh & 
picom &
sh /home/oxy/.config/polybar/launch.sh
